version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 114614701773.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Build started
      - docker build -t demo-ecr .
      - docker tag demo-ecr:latest 114614701773.dkr.ecr.ap-south-1.amazonaws.com/demo-ecr:latest

  post_build:
    commands:
      - echo Pushing image...
      - docker push 114614701773.dkr.ecr.ap-south-1.amazonaws.com/demo-ecr:latest

     
      - printf '[{"name":"frontend","imageUri":"%s"}]' 114614701773.dkr.ecr.ap-south-1.amazonaws.com/demo-ecr:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
